"""
Garage Meeting Copilot — Database Models
SQLAlchemy ORM models for the copilot subsystem.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


class MeetingSession(Base):
    """
    Represents an active or completed copilot session for a Garage meeting.
    References the Garage meeting by external ID — does NOT own meeting data.
    """
    __tablename__ = "meeting_sessions"
    __table_args__ = (
        Index("ix_meeting_sessions_garage_meeting_id", "garage_meeting_id"),
        Index("ix_meeting_sessions_user_id", "user_id"),
        Index("ix_meeting_sessions_workspace_id", "workspace_id"),
        Index("ix_meeting_sessions_status", "status"),
    )

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_uuid,
    )
    garage_meeting_id: Mapped[str] = mapped_column(String(255), nullable=False)
    user_id: Mapped[str] = mapped_column(String(255), nullable=False)
    organization_id: Mapped[str] = mapped_column(String(255), nullable=False)
    workspace_id: Mapped[str] = mapped_column(String(255), nullable=True)
    status: Mapped[str] = mapped_column(String(50), default="active", nullable=False)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    title: Mapped[str | None] = mapped_column(String(200), nullable=True)
    metadata_: Mapped[dict[str, Any]] = mapped_column(
        "metadata",
        JSONB,
        default=dict,
    )

    # Relationships
    transcripts: Mapped[list[TranscriptChunk]] = relationship(
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="TranscriptChunk.sequence_number",
    )
    summaries: Mapped[list[MeetingSummary]] = relationship(
        back_populates="session",
        cascade="all, delete-orphan",
    )
    action_items: Mapped[list[ActionItem]] = relationship(
        back_populates="session",
        cascade="all, delete-orphan",
    )
    ai_interactions: Mapped[list[AIInteraction]] = relationship(
        back_populates="session",
        cascade="all, delete-orphan",
    )


class TranscriptChunk(Base):
    """
    Individual transcript segments from Deepgram streaming.
    Includes speaker diarization, timing, and confidence.
    """
    __tablename__ = "transcript_chunks"
    __table_args__ = (
        Index("ix_transcript_chunks_session_id", "session_id"),
        Index("ix_transcript_chunks_speaker", "speaker_label"),
        Index("ix_transcript_chunks_is_final", "is_final"),
    )

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_uuid,
    )
    session_id: Mapped[str] = mapped_column(
        ForeignKey("meeting_sessions.id", ondelete="CASCADE"),
        nullable=False,
    )
    sequence_number: Mapped[int] = mapped_column(Integer, nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    speaker_label: Mapped[str | None] = mapped_column(String(100), nullable=True)
    start_time: Mapped[float] = mapped_column(Float, default=0.0)
    end_time: Mapped[float] = mapped_column(Float, default=0.0)
    confidence: Mapped[float] = mapped_column(Float, default=0.0)
    is_final: Mapped[bool] = mapped_column(Boolean, default=False)
    qdrant_point_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    session: Mapped[MeetingSession] = relationship(back_populates="transcripts")


class MeetingSummary(Base):
    """
    Rolling AI-generated summaries of the meeting content.
    Generated by LangGraph pipeline at configurable intervals.
    """
    __tablename__ = "meeting_summaries"
    __table_args__ = (
        Index("ix_meeting_summaries_session_id", "session_id"),
        Index("ix_meeting_summaries_summary_type", "summary_type"),
    )

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_uuid,
    )
    session_id: Mapped[str] = mapped_column(
        ForeignKey("meeting_sessions.id", ondelete="CASCADE"),
        nullable=False,
    )
    summary_type: Mapped[str] = mapped_column(
        String(50),
        default="rolling",
        nullable=False,
    )
    content: Mapped[str] = mapped_column(Text, nullable=False)
    transcript_range_start: Mapped[int] = mapped_column(Integer, default=0)
    transcript_range_end: Mapped[int] = mapped_column(Integer, default=0)
    token_count: Mapped[int] = mapped_column(Integer, default=0)
    s3_key: Mapped[str | None] = mapped_column(String(512), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    session: Mapped[MeetingSession] = relationship(back_populates="summaries")


class ActionItem(Base):
    """
    AI-extracted action items from meeting transcript.
    Continuously updated throughout the session.
    """
    __tablename__ = "action_items"
    __table_args__ = (
        Index("ix_action_items_session_id", "session_id"),
        Index("ix_action_items_status", "status"),
        Index("ix_action_items_assignee", "assignee"),
    )

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_uuid,
    )
    session_id: Mapped[str] = mapped_column(
        ForeignKey("meeting_sessions.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    assignee: Mapped[str | None] = mapped_column(String(255), nullable=True)
    due_date: Mapped[str | None] = mapped_column(String(100), nullable=True)
    priority: Mapped[str] = mapped_column(String(20), default="medium")
    status: Mapped[str] = mapped_column(String(50), default="open")
    source_transcript_chunk_id: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )
    confidence_score: Mapped[float] = mapped_column(Float, default=0.9)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )

    session: Mapped[MeetingSession] = relationship(back_populates="action_items")


class AIInteraction(Base):
    """
    Log of AI chat interactions within a meeting session.
    Used for context, history, and analytics.
    """
    __tablename__ = "ai_interactions"
    __table_args__ = (
        Index("ix_ai_interactions_session_id", "session_id"),
        Index("ix_ai_interactions_interaction_type", "interaction_type"),
    )

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_uuid,
    )
    session_id: Mapped[str] = mapped_column(
        ForeignKey("meeting_sessions.id", ondelete="CASCADE"),
        nullable=False,
    )
    interaction_type: Mapped[str] = mapped_column(
        String(50),
        default="chat",
        nullable=False,
    )
    user_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    ai_response: Mapped[str] = mapped_column(Text, nullable=False)
    context_chunks_used: Mapped[list[str]] = mapped_column(JSONB, default=list)
    prompt_tokens: Mapped[int] = mapped_column(Integer, default=0)
    completion_tokens: Mapped[int] = mapped_column(Integer, default=0)
    latency_ms: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    session: Mapped[MeetingSession] = relationship(back_populates="ai_interactions")


class ScreenContext(Base):
    """
    OCR-extracted screen context captured by the desktop agent.
    Used to enhance AI contextual intelligence.
    """
    __tablename__ = "screen_contexts"
    __table_args__ = (
        Index("ix_screen_contexts_session_id", "session_id"),
    )

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_uuid,
    )
    session_id: Mapped[str] = mapped_column(String(255), nullable=False)
    extracted_text: Mapped[str] = mapped_column(Text, nullable=False)
    application_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    window_title: Mapped[str | None] = mapped_column(String(500), nullable=True)
    s3_screenshot_key: Mapped[str | None] = mapped_column(String(512), nullable=True)
    captured_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
